services:
    textpod-docker:
        image: xxmymxue/textpod:0.0.2
        build: .
        ports:
            - '8099:3000'
        volumes:
            - './notes:/app/notes'
        container_name: textpod
        restart: unless-stopped
        environment:
            - TZ=UTC
